# GitHub Action metadata for setup-liquibase
# This action downloads and installs Liquibase (OSS or Pro) for use in GitHub Actions workflows

name: 'Setup Liquibase'
description: 'Set up your GitHub Actions workflow with a specific version of Liquibase'
author: 'Liquibase'

# GitHub Marketplace branding
branding:
  icon: 'database'  # Database icon representing Liquibase's purpose
  color: 'blue'     # Blue color matching Liquibase brand

# Input parameters that users can configure when using this action
inputs:
  version:
    description: 'Version of Liquibase to install. Supports specific versions (e.g., "4.25.0"), version ranges (e.g., "^4.20"), or "latest"'
    required: false
    default: 'latest'
  
  edition:
    description: 'Edition to install: "oss" (Open Source) or "pro" (Professional with additional features). If not specified, auto-detects based on license key presence.'
    required: false
  
  license-key:
    description: 'License key for Liquibase Pro edition. Required when edition is "pro". Store this securely in GitHub Secrets.'
    required: false
  
  cache:
    description: 'Enable caching of downloaded Liquibase installations to improve workflow performance on subsequent runs'
    required: false
    default: 'false'
  
  check-latest:
    description: 'Check for the latest available version that satisfies the version specification, even if a cached version exists'
    required: false
    default: 'false'

# Output values that other workflow steps can use
outputs:
  liquibase-version:
    description: 'The actual version of Liquibase that was installed (useful when using "latest" or version ranges)'
  
  liquibase-path:
    description: 'The file system path where Liquibase was installed and added to PATH'

# Action execution configuration
runs:
  using: 'node20'        # Use Node.js 20 runtime
  main: 'dist/index.js'  # Entry point for the compiled action