name: 'Setup Liquibase'
description: 'Set up your GitHub Actions workflow with a specific version of Liquibase'
author: 'Liquibase'
branding:
  icon: 'database'
  color: 'blue'
inputs:
  version:
    description: 'Version of Liquibase to install. Use "latest" for the most recent version.'
    required: false
    default: 'latest'
  edition:
    description: 'Edition to install: "oss" or "pro"'
    required: false
    default: 'oss'
  liquibase-pro-license-key:
    description: 'License key for Liquibase Pro. Required when edition is "pro".'
    required: false
  cache:
    description: 'Used to specify whether caching is needed. Set to true, if you want to enable caching'
    required: false
    default: 'false'
  check-latest:
    description: 'Set this option if you want the action to check for the latest available version that satisfies the version spec'
    required: false
    default: 'false'
outputs:
  liquibase-version:
    description: 'The actual version of Liquibase that was installed'
  liquibase-path:
    description: 'The path where Liquibase was installed'
runs:
  using: 'node20'
  main: 'dist/index.js'