name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run linting
        run: npm run lint

      - name: Build distribution
        run: npm run build

      - name: Verify build output
        run: |
          if [ ! -f "dist/index.js" ]; then
            echo "dist/index.js not found!"
            exit 1
          fi
          if [ ! -f "dist/index.js.map" ]; then
            echo "dist/index.js.map not found!"
            exit 1
          fi
          echo "Build output verified successfully"

      - name: Test action locally
        uses: ./
        with:
          version: '4.32.0'
          edition: 'oss'
          cache: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit dist files to release
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/
          git commit -m "Add built distribution files for release ${{ github.ref_name }}" || echo "No changes to commit"
          git tag -f ${{ github.ref_name }}
          git push -f origin ${{ github.ref_name }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            dist/index.js
            dist/index.d.ts
            dist/index.js.map
            dist/index.d.ts.map
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update CHANGELOG.md
        uses: TriPSs/conventional-changelog-action@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: './package.json'
          output-file: 'CHANGELOG.md'
          skip-version-file: true
          skip-commit: true
          release-count: 0 