name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Run tests
      run: npm test
    
    - name: Build action
      run: npm run build

  integration-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: ['4.25.0', 'latest']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Test setup-liquibase action
      uses: ./
      with:
        version: ${{ matrix.version }}
        edition: 'oss'
        cache: true
    
    - name: Verify Liquibase installation
      run: liquibase --version